#! /bin/bash

# Setup ------------------------------------------------------------------------

# Program
PROG=ADT # enter program name
HOME=/home/$USER/Scripts/System/DesktopFiles/$PROG

# Icon
ICON_HOME=/usr/share/icons/hicolor
ICON_TYPE=$2
ICON_NAME=$PROG.$ICON_TYPE

# Desktop
DESK_NAME=$PROG.desktop
EXEC=/home/$USER/Scripts/Dev/ADT/ADT_Start.sh # enter execution instructions
MENU=Development # enter menu entry type

# .desktop contents ------------------------------------------------------------

DESK="[Desktop Entry]\n"\
"Type=Application\n"\
"Encoding=UTF-8\n"\
"Name=$PROG\n"\
"Comment=$PROG\n"\
"Exec=$EXEC\n"\
"Icon=$ICON_HOME/64x64/apps/$ICON_NAME\n"\
"Terminal=false\n"\
"Categories=$MENU;"

# Error / Help messages ---------------------------------------------------------

MSG="\nYou need to enter command in the form:\n\n"\
"\tsetup [option] [value]\n\n"\
"options:\n\n"\
"\t-i or --install : create and install .desktop file as well as icons. You "\
"need to specify the icon type to be installed as a value:\n"\
"\t\t> svg\n"\
"\t\t> png\n\n"\
"\t-r or --remove : remove .desktop file and icons.\n\n"

REM_ICON="\n\"No such file or directory\" means icon type was not "\
"previously installed ---^\n"

# ------------------------------------------------------------------------------

case "$1" in
    "-i" | "--install")
    
        # Install Icons
        if [ "$ICON_TYPE" = "png" ]; then
            # PNG
            sudo cp $HOME/icons/64x64/$ICON_NAME \
            $ICON_HOME/64x64/apps/$ICON_NAME    # 64x64
            sudo cp $HOME/icons/48x48/$ICON_NAME \
            $ICON_HOME/48x48/apps/$ICON_NAME    # 48x48
            
        elif [ "$ICON_TYPE" = "svg" ]; then
            # SVG
            sudo cp $HOME/icons/svg/$ICON_NAME \
            $ICON_HOME/64x64/apps/$ICON_NAME    # 64x64
            sudo cp $HOME/icons/svg/$ICON_NAME \
            $ICON_HOME/48x48/apps/$ICON_NAME    # 48x48
            
        else
            echo -e $MSG
            exit 1
        fi
            
        # Create .desktop        
        echo -e $DESK > $HOME/$DESK_NAME

        # Install .desktop
        sudo cp $HOME/$DESK_NAME \
        /usr/share/applications/$DESK_NAME
    ;;
        
    "-r" | "--remove")
    
        # Remove Icons
        sudo rm $ICON_HOME/64x64/apps/$PROG.png # 64x64
        sudo rm $ICON_HOME/64x64/apps/$PROG.svg
        sudo rm $ICON_HOME/48x48/apps/$PROG.png # 48x48
        sudo rm $ICON_HOME/48x48/apps/$PROG.svg
        
        echo -e $REM_ICON
        
        # Remove .desktop
        rm $HOME/$DESK_NAME
        sudo rm /usr/share/applications/$DESK_NAME
    ;;
        
    *)
        echo -e $MSG
    ;;
esac
