#!/bin/bash

#---------------------------------------------------------------------#
#                      Script to set custom PATH                      #
#---------------------------------------------------------------------#


# Set Your PATH Variables Here ----------------------------------------

NEW_PATH='$PATH' # takes PATH generated by ~/.profile

# Java
JAVA_VER=jdk1.7.0_45
JAVA_HOME=/opt/java/$JAVA_VER/bin
NEW_PATH=$JAVA_HOME:$NEW_PATH

# ADT tools
ADT_SDK=/opt/ADT/sdk
P_TOOLS=$ADT_SDK/platform-tools
TOOLS=$ADT_SDK/tools
NEW_PATH=$NEW_PATH:$P_TOOLS:$TOOLS

#----------------------------------------------------------------------


# Add / Remove PATH Variables from ~/.profile -------------------------

COMMENT="# set $USER's PATH" # comment set within ~/.profile

MSG="You MUST now log out to set your PATH." # used in popup

# check if PATH prev set by this script
PATH_SET=$(egrep "^$COMMENT" ~/.profile)

if [ "X$PATH_SET" = "X" ]; then # PATH not previously set
	cp ~/.profile ~/.profile.OLD # backup profile
	printf "\n$COMMENT\n" >> ~/.profile # add comment to ~/.profile
	printf "PATH=$NEW_PATH" >> ~/.profile # add NEW_PATH to ~/.profile
	zenity --info --title="info" --text "$MSG" # info pop-up
else
	cp ~/.profile ~/.profile.OLD # backup profile
	LINE=$(sed -n "/$COMMENT/ =" ~/.profile ) # find comment line number
	LINE=$((LINE+1)) # increment by one to next line
	sed -i -e "$LINE d" ~/.profile # remove line from ~/.profile
	printf "PATH=$NEW_PATH" >> ~/.profile # add NEW_PATH to ~/.profile
	zenity --info --title="info" --text "$MSG" # info pop-up
fi

#----------------------------------------------------------------------
